export {ADD_COLLEGE} from './addCollege';
export {GET_BRANCH_LIST} from './getBranchList';
export {SAVE_BRANCH} from './saveBranch';
export {GET_STATE_LIST} from './getStateList';
export {GET_CITY_LIST} from './getCityList';
export {SAVE_AUTHORIZED_SIGNATORY} from './saveAuthorizedSignatory';
export {GET_AUTHORIZED_SIGNATORY_LIST} from './getAuthorizedSignatoryList';
export {SAVE_BANK_ACCOUNTS} from './saveBankAccounts';
export {GET_BANK_ACCOUNTS_LIST} from './getBankAccountsList';
